apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cls-backend-application.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.workloadIdentity }}
    iam.gke.io/gcp-service-account: {{ include "cls-backend-application.getServiceAccount" . }}@{{ .Values.gcp.project }}.iam.gserviceaccount.com
    {{- end }}
    # Run before application deployment, and migration job
    argocd.argoproj.io/hook: PreSync
